name: onboarding_intro
description: OnBoraring flutter package
version: 0.0.3
author: Ahmed elsayed
homepage: https://www.pharous.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

